version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: react
    versions:
    - 17.0.1
